# action.yml
name: 'Get secrets from hachicorp KV vault'
description: 'Gets secrets'
branding:
  icon: arrow-down-right
  color: red
inputs:
  url:
    description: 'Base url to vault, without /v1 part'
    required: true
  token:
    description: 'Access token to vault'
    required: true
  engine:
    description: 'Name of secret engine'
    required: true
  path:
    description: 'Base path for output'
  debug:
    description: 'Output secret name, type and output file'
runs:
  using: 'composite'
  steps:
    - run: python $GITHUB_ACTION_PATH/main.py ${{ inputs.engine }} ${{ inputs.token }} ${{ inputs.url }} ${{ inputs.path }} ${{ inputs.debug }}
      shell: bash
